language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update && composer install

script:
  - vendor/bin/kahlan --config=kahlan-config.travis.php --coverage=1 --coverage-coveralls="coveralls.json"

after_script:
  - curl -F "json_file=@coveralls.json" https://coveralls.io/api/v1/jobs
